repos:
  - repo: https://github.com/asottile/pre-commit-hooks
    rev: v4.1.0  # Replace with the desired version/tag
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml
